
  create table "public"."chat_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" text,
    "username" text,
    "room_id" bigint
      );


alter table "public"."chat_messages" enable row level security;


  create table "public"."chat_room" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
      );


alter table "public"."chat_room" enable row level security;

CREATE UNIQUE INDEX "chat-room_name_key" ON public.chat_room USING btree (name);

CREATE UNIQUE INDEX "chat-room_pkey" ON public.chat_room USING btree (id);

CREATE UNIQUE INDEX chat_messages_pkey ON public.chat_messages USING btree (id);

alter table "public"."chat_messages" add constraint "chat_messages_pkey" PRIMARY KEY using index "chat_messages_pkey";

alter table "public"."chat_room" add constraint "chat-room_pkey" PRIMARY KEY using index "chat-room_pkey";

alter table "public"."chat_messages" add constraint "chat_messages_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public.chat_room(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."chat_messages" validate constraint "chat_messages_room_id_fkey";

alter table "public"."chat_room" add constraint "chat-room_name_key" UNIQUE using index "chat-room_name_key";

grant delete on table "public"."chat_messages" to "anon";

grant insert on table "public"."chat_messages" to "anon";

grant references on table "public"."chat_messages" to "anon";

grant select on table "public"."chat_messages" to "anon";

grant trigger on table "public"."chat_messages" to "anon";

grant truncate on table "public"."chat_messages" to "anon";

grant update on table "public"."chat_messages" to "anon";

grant delete on table "public"."chat_messages" to "authenticated";

grant insert on table "public"."chat_messages" to "authenticated";

grant references on table "public"."chat_messages" to "authenticated";

grant select on table "public"."chat_messages" to "authenticated";

grant trigger on table "public"."chat_messages" to "authenticated";

grant truncate on table "public"."chat_messages" to "authenticated";

grant update on table "public"."chat_messages" to "authenticated";

grant delete on table "public"."chat_messages" to "postgres";

grant insert on table "public"."chat_messages" to "postgres";

grant references on table "public"."chat_messages" to "postgres";

grant select on table "public"."chat_messages" to "postgres";

grant trigger on table "public"."chat_messages" to "postgres";

grant truncate on table "public"."chat_messages" to "postgres";

grant update on table "public"."chat_messages" to "postgres";

grant delete on table "public"."chat_messages" to "service_role";

grant insert on table "public"."chat_messages" to "service_role";

grant references on table "public"."chat_messages" to "service_role";

grant select on table "public"."chat_messages" to "service_role";

grant trigger on table "public"."chat_messages" to "service_role";

grant truncate on table "public"."chat_messages" to "service_role";

grant update on table "public"."chat_messages" to "service_role";

grant delete on table "public"."chat_room" to "anon";

grant insert on table "public"."chat_room" to "anon";

grant references on table "public"."chat_room" to "anon";

grant select on table "public"."chat_room" to "anon";

grant trigger on table "public"."chat_room" to "anon";

grant truncate on table "public"."chat_room" to "anon";

grant update on table "public"."chat_room" to "anon";

grant delete on table "public"."chat_room" to "authenticated";

grant insert on table "public"."chat_room" to "authenticated";

grant references on table "public"."chat_room" to "authenticated";

grant select on table "public"."chat_room" to "authenticated";

grant trigger on table "public"."chat_room" to "authenticated";

grant truncate on table "public"."chat_room" to "authenticated";

grant update on table "public"."chat_room" to "authenticated";

grant delete on table "public"."chat_room" to "postgres";

grant insert on table "public"."chat_room" to "postgres";

grant references on table "public"."chat_room" to "postgres";

grant select on table "public"."chat_room" to "postgres";

grant trigger on table "public"."chat_room" to "postgres";

grant truncate on table "public"."chat_room" to "postgres";

grant update on table "public"."chat_room" to "postgres";

grant delete on table "public"."chat_room" to "service_role";

grant insert on table "public"."chat_room" to "service_role";

grant references on table "public"."chat_room" to "service_role";

grant select on table "public"."chat_room" to "service_role";

grant trigger on table "public"."chat_room" to "service_role";

grant truncate on table "public"."chat_room" to "service_role";

grant update on table "public"."chat_room" to "service_role";


